pipeline {
  agent any
  environment {
    NODE_ENV = "development"
  }
  stages {
    stage('S1') {
      steps {
        sh '''
          echo "Stage 'BUILD' is starting"
          echo "NODE_ENV = ${NODE_ENV}"
        '''
      }
    }
    stage('S2') {
      steps {
        sh '''
          echo "Stage 'LINT' is starting"
        '''
      }
    }
    stage('S3') {
      steps {
        sh '''
          echo "Stage 'TEST' is starting"
        '''
      }
    }
  }
}