FROM lissy93/dashy

# RUN apt install sudo -y
# RUN sudo apt update
# RUN sudo apt install nano -y
# RUN sudo usermod -aG sudo admin
# RUN sudo usermod --password $(openssl passwd -6 '<your_password>') <user>
# RUN sudo useradd -m -s /bin/bash -G sudo admin
# RUN echo "admin:Qwerty1!" | sudo chpasswd
# USER admin
# RUN addgroup --g 1000 groupcontainer
# RUN adduser -u 1000 -G groupcontainer -h /home/containeruser -D containeruser

# cat /etc/group                                                      # посмотреть принадлежность sudo
# su - <newuser>                                                   # одна тире

# USER containeruser

# COPY test.txt /home/containeruser/test.txt
# CMD ["tail", "-f", "/dev/null"]